config/routes.rb
Rails.application.routes.draw do
  resources :organisations
  resources :users
  resources :menus
  resources :options
  resources :orders
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :organisation
  has_many :menu_options, dependent: :destroy
  has_many :options, through: :menu_options, dependent: :destroy
  accepts_nested_attributes_for :menu_options, allow_destroy: true
end

app/models/menu_option.rb
class MenuOption < ApplicationRecord
  belongs_to :menu
  belongs_to :option
end

app/models/option.rb
class Option < ApplicationRecord
  has_many :menu_options, dependent: :destroy
  has_many :menus, through: :menu_options
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :option
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  has_many :menus
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :organisation, optional: true

  def self.is_in_org(auth)
    !!(where(email: auth.info.email).first.try(:organisation_id?))
  end

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.photo = auth.info.image
      user.google_token = auth.credentials.token
      user.google_refresh_token = auth.credentials.refresh_token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :require_user!
  before_action :set_menu, only: [:edit, :update]
  
  def index
    @menus = Menu.where(organisation: helpers.current_user.organisation)
  end

  def new
    @menu = Menu.new
    @menu.menu_options.build
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.organisation = helpers.current_user.organisation
    respond_to do |format|
      if @menu.save
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @menu.update
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def require_user!
      if !helpers.logged_in?
        redirect_to root_path
        flash[:alert] = "You must be logged in to view menus."
      end
    end

    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params.require(:menu).permit(:id, :date, option_ids: [])
    end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :require_admin!
  before_action :set_option, only: [:edit, :update]

  def index
    @options = Option.all
  end

  def new
    @option = Option.new
  end

  def edit
  end

  def create
    @option = Option.new(option_params)
    respond_to do |format|
      if @option.save
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @option.save
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def require_admin!
      if !helpers.current_user.try(:admin?)
        redirect_to menus_path
        flash[:alert] = "You must be an admin to view options."
      end
    end

    def set_option
      @option = Option.find(params[:id])
    end

    def option_params
      params.require(:option).permit(:description)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_user!
  before_action :set_order, only: [:edit, :update]
  
  def index
    @orders = Order.all
    dates = @orders.pluck(:date).uniq
    @order_lists = dates.map { |d| {date: d, orders: @orders.where(date: d)} }
  end

  def new
    @order = Order.new
    @menu = Menu.find(params[:menu])
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.user = helpers.current_user
    respond_to do |format|
      if @order.save
        format.html { redirect_to menus_path }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update
        format.html { redirect_to menus_path }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def require_user!
      if !helpers.logged_in?
        redirect_to root_path
        flash[:alert] = "You must be logged in to view orders."
      end
    end

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:date, :option_id, :notes)
    end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :require_admin!
  
  def new
    @organisation = Organisation.new
  end

  def edit
  end

  def create
    @organisation = Organisation.new(organisation_params)
    respond_to do |format|
      if @organisation.save
        @user = helpers.current_user
        @user.organisation = @organisation
        @user.admin = true
        @user.save
        format.html { redirect_to menus_path }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def require_admin!
      if !helpers.current_user.try(:admin?)
        redirect_to menus_path
        flash[:alert] = "You must be an admin to edit organisations."
      end
    end

    def organisation_params
      params.require(:organisation).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def omniauth
    is_in_org = User.is_in_org(auth)
    @user = User.from_omniauth(auth)
    session[:user_id] = @user.id
    @user.save
    redirect_to is_in_org ? menus_path : new_organisation_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def auth
      request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin!, except: [:index]
  def index
    @users = User.where(organisation: helpers.current_user.organisation)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.organisation = helpers.current_user.organisation
    respond_to do |format|
      if @user.save
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def require_admin!
      if !helpers.current_user.try(:admin?)
        redirect_to menus_path
        flash[:alert] = "You must be an admin to edit users."
      end
    end

    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/views/home/index.html.erb
<h1 class="text-xl my-5">🥪 Welcome to Lunch Time!</h1>
<% if logged_in? %>
  <%= link_to logout_path, class: "bg-red-500 text-white rounded p-1" do %>
    <%= fa_icon "sign-out" %> Log out
  <% end %>
<% else %>
  <%= link_to '/auth/google_oauth2', class: "bg-teal-500 text-white rounded p-1" do %>
    <%= fa_icon "google" %> Sign in with Google
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="bg-<%= key == 'error' ? 'red' : key == 'alert' ? 'yellow' : 'teal' %>-200 border border-<%= key == 'error' ? 'red' : key == 'alert' ? 'yellow' : 'teal' %>-400 px-4 py-3 rounded flex flex-row justify-between" role="alert">
    <span>
      <%= value %>
    </span>
    <a href="#" data-dismiss="alert" class="close"><%= fa_icon "times" %></a>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="bg-<%= current_user.try(:admin?) ? 'blue' : 'teal' %>-500">
  <div class="flex items-center justify-between flex-wrap max-w-5xl m-auto p-6">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <%= link_to "Lunch Time", root_path, class: "font-semibold text-xl tracking-tight" %>
    </div>
    <div class="block lg:hidden">
      <button id="menu_button" class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div id="menu" class="hidden w-full flex-grow lg:flex lg:flex-row lg:items-center lg:justify-between lg:w-auto">
      <div class="text-sm">
        <%= link_to "Menus", menus_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to "Orders", orders_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <% if current_user.try(:admin?) %>
          <%= link_to "Options", options_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
          <%= link_to "Users", users_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <% end %>
      </div>
      <% if logged_in? %>
        <div class="flex flex-row items-center mt-4 lg:mt-0">
          <% if current_user.photo %>
            <%= image_tag current_user.photo, size: "30x30" %>
          <% end %>
          <%= link_to logout_path, class: "ml-3 text-teal-200 hover:text-white mr-4" do %>
            <%= fa_icon "sign-out" %> Log out
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LunchTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('apple-touch-icon.png'), rel: "apple-touch-icon", sizes: "180x180" %>
    <%= favicon_link_tag asset_path('favicon-32x32.png'), rel: "icon", type: "image/png", sizes: "32x32" %>
    <%= favicon_link_tag asset_path('favicon-16x16.png'), rel: "icon", type: "image/png", sizes: "16x16" %>
  </head>

  <body class="bg-gray-200">
    <% if logged_in? %>
      <%= render 'layouts/nav' %>
    <% end %>
    <main class="px-6 py-4 max-w-5xl m-auto">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with model: @menu do |form| %>
  <div class="py-3">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="py-3 flex flex-col">
    <small>Please tick all the options available for this menu</small>
    <%= form.collection_check_boxes :option_ids, Option.all, :id, :description, {}, {multiple: true} do |b| %>
      <%= b.label do %>
        <%= b.check_box %> <%= b.text %>
      <% end %>
    <% end %>
  </div>

  <%= form.submit class: "bg-teal-400 text-white rounded p-1" %>
<% end %>

app/views/menus/edit.html.erb
<h2 class="text-xl">Edit Menu</h2>
<%= render 'form' %>

app/views/menus/index.html.erb
<div class="flex flex-row justify-between mb-2">
  <h2 class="text-xl">Menus</h2>
  <% if current_user.try(:admin?) %>
    <%= link_to new_menu_path, class: "bg-teal-400 text-white rounded p-1" do %>
      <%= fa_icon "plus" %> New menu
    <% end %>
  <% end %>
</div>
<div class="grid md:grid-cols-2 gap-2">
  <% @menus.each do |m| %>
    <div class="rounded shadow-lg p-2 bg-white flex flex-row justify-between">
      <div>
        <h3><%= m.date.strftime("%a %e %b %y") %></h3>
        <ul>
          <% m.options.each do |option| %>
            <li class="text-sm"><%= option.description %></li>
          <% end %>
        </ul>
      </div>
      <% if current_user.try(:admin?) %>
        <%= link_to  edit_menu_path(m) do %>
          <%= fa_icon "edit" %> Edit
        <% end %>
      <% else %>
        <%= link_to "Order", new_order_path(menu: m) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/menus/new.html.erb
<h2 class="text-xl">New Menu</h2>
<%= render 'form' %>

app/views/options/_form.html.erb
<%= form_with model: @option do |form| %>
  <div class="py-3 flex flex-col">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%= form.submit class: "bg-teal-400 text-white rounded p-1" %>
<% end %>

app/views/options/edit.html.erb
<h2 class="text-xl">Edit Option</h2>
<%= render 'form' %>

app/views/options/index.html.erb
<div class="flex flex-row justify-between mb-2">
  <h2 class="text-xl">Options</h2>
  <%= link_to new_option_path, class: "bg-teal-400 text-white rounded p-1" do %>
    <%= fa_icon "plus" %> New option
  <% end %>
</div>
<ul class="grid md:grid-cols-2 lg:grid-cols-3 gap-2">
  <% @options.each do |o| %>
    <li class="rounded shadow-lg p-2 bg-white flex flex-row justify-between">
      <%= o.description %>
      <%= link_to edit_option_path(o) do %>
        <%= fa_icon "edit" %> Edit
      <% end %>
    </li>
  <% end %>
</ul>

app/views/options/new.html.erb
<h2 class="text-xl">New Option</h2>
<%= render 'form' %>

app/views/orders/_form.html.erb
<%= form_with model: @order do |form| %>
  <%= form.hidden_field :date, value: @menu.date %>

  <div class="py-3 flex flex-col">
    <%= form.collection_select :option_id, @menu.options, :id, :description do |b| %>
      <%= b.label do %>
        <%= b.check_box %> <%= b.text %>
      <% end %>
    <% end %>
  </div>

  <div class="py-3 flex flex-col">
    <small>Please add any notes e.g. likes / dislikes</small>
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <%= form.submit class: "bg-teal-400 text-white rounded p-1" %>
<% end %>

app/views/orders/index.html.erb
<div class="flex flex-row justify-between mb-2">
  <h2 class="text-xl">Orders</h2>
</div>
<% @order_lists.each do |ol| %>
  <h3><%= fa_icon "calendar-o" %> <%= ol[:date].strftime("%a %e %b %y") %></h3>
  <div class="grid md:grid-cols-2 gap-2">
    <% ol[:orders].each do |o| %>
      <div class="rounded shadow-lg p-2 bg-white flex flex-row justify-between">
        <div>
          <p class="text-sm"><%= fa_icon "user-circle" %> <%= o.user.name || o.user.email %></p>
          <p class="text-sm">
            <%= fa_icon "cutlery" %> <%= o.option.description %>
            <% if o.notes.present? %>
              • <%= o.notes %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h2 class="text-xl">Order for <%= @menu.date.strftime("%a %e %b %y") %></h2>
<%= render 'form' %>

app/views/organisations/new.html.erb
<h2 class="text-xl">New Organisation</h2>
<p>You have signed in successfully with Google</p>
<p>Please create a new organisation to start adding users and menus.</p>
<%= form_with model: @organisation do |form| %>
  <div class="py-3 flex flex-col">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.submit class: "bg-teal-400 text-white rounded p-1" %>
<% end %>

app/views/users/index.html.erb
<div class="flex flex-row justify-between mb-2">
  <h2 class="text-xl">Users in <%= current_user.organisation.name %></h2>
  <%= link_to new_user_path, class: "bg-teal-400 text-white rounded p-1" do %>
    <%= fa_icon "plus" %> New user
  <% end %>
</div>
<ul class="grid md:grid-cols-2 lg:grid-cols-3 gap-2">
  <% @users.each do |u| %>
    <li class="rounded shadow-lg p-2 bg-white flex flex-row justify-between">
      <%= u.name || u.email %>
      <% if u.try(:admin?) %>
        <span><%= fa_icon "user" %> Admin</span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2 class="text-xl">New User</h2>
<%= form_with model: @user do |form| %>
  <div class="py-3 flex flex-col">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <%= form.submit class: "bg-teal-400 text-white rounded p-1" %>
<% end %>